/**
 * Gom Yapper — Corpus
 *
 * Static data bank: archetype definitions, templates, and slot fillers.
 * Phase 1: 3 archetypes (Ratio Guy, Crypto Bro, Unhinged Reply Guy).
 */

const GOM_CORPUS = {
  archetypes: [
    {
      id: 'ratio_guy',
      name: 'Ratio Guy',
      weight: 20,
      templates: [
        'ratio',
        'L',
        'nobody asked',
        'cope',
        '{insult}',
        'L + {insult}',
        'ratio + {insult}',
        'didn\'t ask + {insult}',
        'cool story bro',
        'you thought you did something here',
        'this ain\'t it chief',
        'massive L',
        'the audacity of this tweet',
        'go outside',
        'tell me you have no friends without telling me you have no friends',
        'least delusional twitter user',
        'bro really thought he cooked 💀',
        'imagine posting this and thinking it was good',
        'you\'re the reason people leave this app',
        'mid take',
        'the silence from everyone who agrees with you is deafening',
        'bro woke up and chose to be wrong',
        'L take + ratio + {insult}',
        'not reading all that. {insult}',
        'ok and?',
      ],
    },
    {
      id: 'crypto_bro',
      name: 'Crypto Bro',
      weight: 15,
      templates: [
        'this is why you need to look into {coin}. {shill_phrase}',
        'imagine caring about this when {coin} is about to do a 10x. {shill_phrase}',
        'bro you could be making money instead of tweeting this. check out {coin}. {shill_phrase}',
        'this is what happens when you don\'t hold {coin}. {shill_phrase}',
        'the real ratio is your portfolio lol. get into {coin}. {shill_phrase}',
        'not financial advice but {coin} is literally free money rn. {shill_phrase}',
        'you wouldn\'t be this mad if you aped into {coin} last week',
        'ser this is a {coin} thread now. {shill_phrase}',
        'anon, respectfully, have fun staying poor. {coin} is the way. {shill_phrase}',
        'bullish on the opposite of whatever this take is. buying more {coin}',
        'few understand. {coin} fixes this. {shill_phrase}',
        '{coin} up 400% and you\'re posting this lmaooo',
        'the market doesn\'t care about your feelings. {coin}. {shill_phrase}',
        'this tweet has the same energy as selling {coin} at the bottom',
        'ngmi with takes like this. meanwhile {coin} holders eating. {shill_phrase}',
        'imagine the regret when {coin} hits $100. {shill_phrase}',
        'just mass-reported this tweet for being bearish on {coin}',
        'you could afford therapy if you bought {coin} when I told you to',
        'twitter take: 0/10. {coin} chart: 10/10. {shill_phrase}',
        'my {coin} bag doesn\'t care about your opinion. {shill_phrase}',
      ],
    },
    {
      id: 'unhinged_reply_guy',
      name: 'Unhinged Reply Guy',
      weight: 15,
      templates: [
        'I cannot BELIEVE you would say this. {overreaction}. Blocked.',
        'WOW. just WOW. {overreaction}',
        'THIS is what\'s wrong with this website. {overreaction}',
        'I just showed this to my therapist and she started crying',
        'my blood pressure literally just spiked reading this. {overreaction}',
        'I have been SHAKING for the last twenty minutes because of this tweet. {overreaction}',
        'you have NO IDEA the damage this tweet has caused. {overreaction}',
        'I was having a good day until I read this. {overreaction}',
        'actually screaming at my phone right now. {overreaction}',
        'this is genuinely the most harmful thing I have ever read on this website',
        'I am going to remember this tweet on my deathbed and it will ruin my last moments',
        'every day I log on and someone like you makes it worse. {overreaction}',
        'DO YOU EVEN HEAR YOURSELF?? {overreaction}',
        'I just threw my phone across the room reading this. {overreaction}',
        'this tweet is violence. actual violence. {overreaction}',
        'I need to lie down after reading this. {overreaction}',
        'showed this tweet to my cat and he hissed at the screen',
        'I have officially lost all faith in humanity thanks to this ONE tweet. {overreaction}',
        'bro dropped this take and thought we\'d all just be OKAY with it??? {overreaction}',
        'the NERVE. the ABSOLUTE AUDACITY. {overreaction}',
      ],
    },
  ],

  fillers: {
    insult: [
      'this ain\'t it',
      'touch grass',
      'most sane twitter user',
      'least brain-damaged take',
      'certified clown behavior',
      'you dropped this 🤡',
      'absolute room-temperature IQ take',
      'bro thinks he\'s deep',
      'galaxy brain moment',
      'average main character syndrome',
      'tell your mom I said hi',
      'least chronically online take',
      'bro peaked in middle school',
      'the bar is in hell and you brought a shovel',
      'most well-adjusted reply guy',
      'this is why nobody follows you back',
      'congrats on the worst take of the day',
      'you\'re not even wrong you\'re just boring',
      'actual NPC behavior',
      'and I thought MY takes were bad',
      'imagine typing this and hitting send',
      'the secondhand embarrassment is real',
      'this is a cry for help',
      'my guy thinks he ate',
      'bless your heart',
      'log off and rethink everything',
      'this tweet belongs in a museum of bad opinions',
      'did a bot write this',
      'most coherent twitter user',
      'please go outside and touch a tree',
      'you really woke up and chose violence against common sense',
      'the hottest of garbage takes',
      'I\'ve seen better takes from fortune cookies',
      'this reads like a cry for attention',
      'congratulations this is the dumbest thing I\'ve read today',
      'bro is fighting for his life in these replies',
      'this take is so cold it lowered the room temperature',
      'seek professional help',
      'most original twitter user',
      'least deranged poster',
      'go back to Facebook',
      'your WiFi should have cut out before you posted this',
      'even your autocorrect is embarrassed',
      'the algorithm should bury this',
      'I need eye bleach after reading this',
      'sir this is a Wendy\'s',
      'you\'re living proof that the internet was a mistake',
      'someone come get their uncle',
      'most self-aware poster on this app',
      'main character syndrome is treatable btw',
    ],

    coin: [
      '$YAPPR',
      '$MOONRUG',
      '$COPIUM',
      '$RUGPULL',
      '$BAGHOLD',
      '$NGMI',
      '$WAGMI',
      '$SEETHE',
      '$HOPIUM',
      '$FUDCOIN',
      '$GIGABRAIN',
      '$PEPEMAX',
      '$DUMPEET',
      '$APECOIN',
      '$PONZI42',
      '$LAMBO',
      '$REKTD',
      '$DIAMONDHAND',
      '$YEETCOIN',
      '$TRUSTMEBRO',
      '$EXIT',
      '$SCAMWICK',
      '$PUMPFUN',
      '$ANONFREN',
      '$DEGENX',
      '$BAGHOLDER',
      '$NOTASCAM',
      '$MEMECAP',
      '$DOWNBAD',
      '$UPONLY',
    ],

    shill_phrase: [
      'still early',
      'NFA but DYOR',
      'wagmi',
      'few understand',
      'this is the way',
      'LFG 🚀',
      'not financial advice',
      'gonna make it',
      'we\'re all gonna make it',
      'bullish af',
      'diamond hands only',
      'ngmi if you don\'t ape in',
      'trust the process',
      'moon soon',
      'generational wealth opportunity',
      'the chart speaks for itself',
      'early is the new late',
      'devs are doxxed',
      'audit coming soon',
      'community-driven',
    ],

    overreaction: [
      'this is literally the worst take of 2024',
      'my therapist is going to hear about this',
      'I am calling the authorities',
      'this should be illegal',
      'you have ruined my entire week',
      'my ancestors are rolling in their graves',
      'I\'m going to need a moment',
      'I can feel my life force draining',
      'humanity was a mistake and this proves it',
      'I\'m uninstalling the internet',
      'this is a crime against common sense',
      'I\'m filing a formal complaint',
      'this tweet set us back as a species',
      'I\'m contacting my congressman about this',
      'this is why aliens won\'t visit us',
      'my faith in humanity: shattered',
      'I have never been more offended in my entire life',
      'this tweet should be studied by scientists',
      'you owe me reparations for making me read this',
      'I\'m adding this to my list of reasons to leave the planet',
      'the Geneva Convention should cover this',
      'I am VISIBLY upset',
      'my doctor said to avoid stress and then I saw this tweet',
      'this is a violation of my human rights',
      'I need to call my mom after reading this',
      'congratulations you have broken me',
      'this tweet gave me a migraine',
      'I\'m never recovering from this',
      'the damage is irreversible',
      'I can\'t even look at my phone anymore',
      'this tweet ended my career somehow',
      'I\'m telling everyone I know about this',
      'the trauma from reading this is immeasurable',
      'I have lost the ability to even',
      'every cell in my body just cringed',
      'I aged ten years reading this',
      'my fight-or-flight just activated',
      'I\'m writing a letter to someone important about this',
      'you should be banned from the internet',
      'this tweet physically hurt me',
    ],
  },

  // Identity generation material
  identity: {
    firstNames: [
      'Jake', 'Mike', 'Kyle', 'Chad', 'Bryce', 'Tyler', 'Hunter', 'Cody',
      'Dylan', 'Logan', 'Mason', 'Austin', 'Caleb', 'Brandon', 'Derek',
      'Alex', 'Jordan', 'Taylor', 'Morgan', 'Casey', 'Riley', 'Quinn',
      'Avery', 'Reese', 'Parker', 'Drew', 'Blake', 'Sage', 'Finn',
      'CryptoKing', 'NFTMaxi', 'DeFiDegen', 'TokenLord',
      'truth', 'freedom', 'based', 'alpha', 'sigma', 'grind',
      'realone', 'patriot', 'thinker', 'hustler',
    ],

    lastFragments: [
      'Official', 'Real', 'Based', 'Actual', 'NotABot', 'TheTruth',
      'Enjoyer', 'Maxi', 'Holder', 'Poster', 'Takes', 'Thoughts',
      'Wins', 'Gains', 'Alpha', 'Sigma', 'Grindset', 'Mindset',
    ],

    handlePatterns: [
      '{first}{4digit}',        // jake8294
      '{first}_{fragment}',     // real_thoughts
      '{adj}{noun}{2digit}',    // basedtakes99
      '{first}{year}',          // mike1997
    ],

    adjectives: [
      'based', 'real', 'true', 'actual', 'raw', 'pure', 'big', 'dark',
      'cold', 'hard', 'mad', 'lit', 'hot', 'top', 'main', 'full',
    ],

    nouns: [
      'takes', 'facts', 'truth', 'alpha', 'gains', 'posts', 'chad',
      'king', 'boss', 'wolf', 'lion', 'bear', 'dude', 'bro', 'guy',
    ],
  },
};
