/**
 * Gom Yapper — Corpus
 *
 * Static data bank: archetype definitions, templates, and slot fillers.
 * Phase 2: All 8 archetypes with full template banks.
 */

const GOM_CORPUS = {
  archetypes: [
    {
      id: 'ratio_guy',
      name: 'Ratio Guy',
      weight: 20,
      templates: [
        'ratio',
        'L',
        'nobody asked',
        'cope',
        '{insult}',
        'L + {insult}',
        'ratio + {insult}',
        'didn\'t ask + {insult}',
        'cool story bro',
        'you thought you did something here',
        'this ain\'t it chief',
        'massive L',
        'the audacity of this tweet',
        'go outside',
        'tell me you have no friends without telling me you have no friends',
        'least delusional twitter user',
        'bro really thought he cooked 💀',
        'imagine posting this and thinking it was good',
        'you\'re the reason people leave this app',
        'mid take',
        'the silence from everyone who agrees with you is deafening',
        'bro woke up and chose to be wrong',
        'L take + ratio + {insult}',
        'not reading all that. {insult}',
        'ok and?',
      ],
    },
    {
      id: 'crypto_bro',
      name: 'Crypto Bro',
      weight: 15,
      templates: [
        'this is why you need to look into {coin}. {shill_phrase}',
        'imagine caring about this when {coin} is about to do a 10x. {shill_phrase}',
        'bro you could be making money instead of tweeting this. check out {coin}. {shill_phrase}',
        'this is what happens when you don\'t hold {coin}. {shill_phrase}',
        'the real ratio is your portfolio lol. get into {coin}. {shill_phrase}',
        'not financial advice but {coin} is literally free money rn. {shill_phrase}',
        'you wouldn\'t be this mad if you aped into {coin} last week',
        'ser this is a {coin} thread now. {shill_phrase}',
        'anon, respectfully, have fun staying poor. {coin} is the way. {shill_phrase}',
        'bullish on the opposite of whatever this take is. buying more {coin}',
        'few understand. {coin} fixes this. {shill_phrase}',
        '{coin} up 400% and you\'re posting this lmaooo',
        'the market doesn\'t care about your feelings. {coin}. {shill_phrase}',
        'this tweet has the same energy as selling {coin} at the bottom',
        'ngmi with takes like this. meanwhile {coin} holders eating. {shill_phrase}',
        'imagine the regret when {coin} hits $100. {shill_phrase}',
        'just mass-reported this tweet for being bearish on {coin}',
        'you could afford therapy if you bought {coin} when I told you to',
        'twitter take: 0/10. {coin} chart: 10/10. {shill_phrase}',
        'my {coin} bag doesn\'t care about your opinion. {shill_phrase}',
      ],
    },
    {
      id: 'unhinged_reply_guy',
      name: 'Unhinged Reply Guy',
      weight: 15,
      templates: [
        'I cannot BELIEVE you would say this. {overreaction}. Blocked.',
        'WOW. just WOW. {overreaction}',
        'THIS is what\'s wrong with this website. {overreaction}',
        'I just showed this to my therapist and she started crying',
        'my blood pressure literally just spiked reading this. {overreaction}',
        'I have been SHAKING for the last twenty minutes because of this tweet. {overreaction}',
        'you have NO IDEA the damage this tweet has caused. {overreaction}',
        'I was having a good day until I read this. {overreaction}',
        'actually screaming at my phone right now. {overreaction}',
        'this is genuinely the most harmful thing I have ever read on this website',
        'I am going to remember this tweet on my deathbed and it will ruin my last moments',
        'every day I log on and someone like you makes it worse. {overreaction}',
        'DO YOU EVEN HEAR YOURSELF?? {overreaction}',
        'I just threw my phone across the room reading this. {overreaction}',
        'this tweet is violence. actual violence. {overreaction}',
        'I need to lie down after reading this. {overreaction}',
        'showed this tweet to my cat and he hissed at the screen',
        'I have officially lost all faith in humanity thanks to this ONE tweet. {overreaction}',
        'bro dropped this take and thought we\'d all just be OKAY with it??? {overreaction}',
        'the NERVE. the ABSOLUTE AUDACITY. {overreaction}',
      ],
    },
    {
      id: 'pseudo_intellectual',
      name: 'Pseudo-Intellectual',
      weight: 12,
      templates: [
        'tell me you don\'t understand {concept} without telling me you don\'t understand {concept}',
        'this is what happens when people who don\'t understand {concept} try to have opinions',
        'actually, if you understood {concept}, you wouldn\'t have posted this',
        'I studied {concept} for years and this is the most reductive take I\'ve ever seen',
        'the Dunning-Kruger is strong with this one. read up on {concept}',
        'imagine not understanding {concept} and still tweeting confidently about it',
        'this take reveals a fundamental misunderstanding of {concept}',
        'I would explain why you\'re wrong but it requires understanding {concept}',
        'sir, this is not the flex you think it is. {concept} says otherwise',
        'spoken like someone who has never once engaged with {concept}',
        'the irony of posting this while clearly not understanding {concept} is *chef\'s kiss*',
        'maybe read a book on {concept} before tweeting next time',
        'this is the kind of take that makes {concept} researchers weep',
        'my brother in christ, {concept} has entered the chat',
        'fascinating case study in not understanding {concept}',
        'you\'re so close to getting it but {concept} is clearly not your strong suit',
        'ah yes, the classic "I don\'t understand {concept}" tweet. seen a million of these',
        'this screams "I read one article about {concept} and formed my entire worldview"',
        'it\'s giving {concept} illiteracy',
        'not to be that guy but {concept} literally disproves everything you just said',
        'bro skipped the chapter on {concept} and it shows',
        'every {concept} expert I know is laughing at this tweet rn',
      ],
    },
    {
      id: 'the_bot',
      name: 'The Bot',
      weight: 15,
      templates: [
        '{emoji_spam} Amazing post! Check out my {spam_product}',
        '{emoji_spam} So true! {spam_product} for more content like this',
        'Great tweet! {emoji_spam} Check my {spam_product}',
        '{emoji_spam} This is incredible! Follow for more. {spam_product}',
        'Love this! {emoji_spam} {spam_product}',
        '{emoji_spam} Wow amazing content! DM me about {spam_product}',
        'This!! {emoji_spam} Link in {spam_product}',
        '{emoji_spam} Best tweet I\'ve seen today! Check {spam_product}',
        'So inspirational {emoji_spam} My {spam_product} has similar energy',
        '{emoji_spam} YES! This is what Twitter needs! {spam_product}',
        'Facts! {emoji_spam} Speaking of which, {spam_product}',
        '{emoji_spam} Couldn\'t agree more! Check out my {spam_product} {emoji_spam}',
        'This changed my life {emoji_spam} Just like my {spam_product}',
        '{emoji_spam} W tweet! Don\'t miss my {spam_product}',
        'I promote people for free {emoji_spam} check my {spam_product}',
        '{emoji_spam} This is gold! {spam_product} for daily gems',
        'Absolutely based {emoji_spam} See my {spam_product} for proof',
        '{emoji_spam} Someone needed to say it! Also check {spam_product}',
        'You spittin {emoji_spam} My {spam_product} is spittin too',
        '{emoji_spam} Real talk! {spam_product} if you agree',
        'Big if true {emoji_spam} Bigger if you check my {spam_product}',
      ],
    },
    {
      id: 'concern_troll',
      name: 'Concern Troll',
      weight: 8,
      templates: [
        'I mean this in the nicest way but {backhanded_concern}',
        'not trying to be mean but {backhanded_concern}',
        'genuinely asking this out of concern: {backhanded_concern}',
        'hey, just looking out for you here — {backhanded_concern}',
        'I say this with love: {backhanded_concern}',
        'no hate, but honestly? {backhanded_concern}',
        'this is coming from a good place I promise: {backhanded_concern}',
        'look, I\'m not judging, but {backhanded_concern}',
        'as someone who cares about you as a stranger on the internet: {backhanded_concern}',
        'I hope you have people in your life who can tell you this gently: {backhanded_concern}',
        'don\'t take this the wrong way but {backhanded_concern}',
        'with all due respect, and I mean that sincerely, {backhanded_concern}',
        'I\'m sure you mean well but {backhanded_concern}',
        'just some friendly feedback: {backhanded_concern}',
        'no offense intended but {backhanded_concern}',
        'as a friend, well, a follower, well, someone who saw this tweet: {backhanded_concern}',
        'this is hard to say but someone needs to: {backhanded_concern}',
        'I really don\'t want to pile on here but {backhanded_concern}',
        'I know this will sound harsh but it\'s for your own good: {backhanded_concern}',
        'bless your heart, but {backhanded_concern}',
        'I only say this because I care: {backhanded_concern}',
      ],
    },
    {
      id: 'off_topic_ranter',
      name: 'Off-Topic Ranter',
      weight: 10,
      templates: [
        'speaking of which, {unrelated_rant}',
        'this reminds me — {unrelated_rant}',
        'not related but {unrelated_rant}',
        'idk why this made me think of this but {unrelated_rant}',
        'anyway {unrelated_rant}',
        'ok but can we talk about how {unrelated_rant}',
        'unrelated but {unrelated_rant}',
        'nobody\'s talking about the real issue here which is that {unrelated_rant}',
        'sure but meanwhile {unrelated_rant}',
        'while we\'re all distracted by this tweet, {unrelated_rant}',
        'this is fine but honestly {unrelated_rant}',
        'I\'ll get to this in a sec but first: {unrelated_rant}',
        'cool tweet. anyway, {unrelated_rant}',
        'ok I hear you but also {unrelated_rant}',
        'you know what\'s actually important? {unrelated_rant}',
        'since everyone\'s here: {unrelated_rant}',
        'weird hill to die on when {unrelated_rant}',
        'the REAL take is that {unrelated_rant}',
        'I know this is off topic but {unrelated_rant}',
        'that\'s great and all but {unrelated_rant}',
        'filing this tweet under "things that don\'t matter" because {unrelated_rant}',
      ],
    },
    {
      id: 'one_word_oracle',
      name: 'One-Word Oracle',
      weight: 5,
      templates: [
        'no',
        'wrong',
        'lol',
        'mid',
        'ok',
        'sure',
        'yikes',
        'nah',
        'false',
        'cap',
        'cringe',
        'based',
        'oof',
        'eh',
        'meh',
        'k',
        'bruh',
        'next',
        'pass',
        'delete this',
        'who asked',
        'and?',
        'so?',
        '💀',
        '🤡',
        'what',
      ],
    },
  ],

  fillers: {
    insult: [
      'this ain\'t it',
      'touch grass',
      'most sane twitter user',
      'least brain-damaged take',
      'certified clown behavior',
      'you dropped this 🤡',
      'absolute room-temperature IQ take',
      'bro thinks he\'s deep',
      'galaxy brain moment',
      'average main character syndrome',
      'tell your mom I said hi',
      'least chronically online take',
      'bro peaked in middle school',
      'the bar is in hell and you brought a shovel',
      'most well-adjusted reply guy',
      'this is why nobody follows you back',
      'congrats on the worst take of the day',
      'you\'re not even wrong you\'re just boring',
      'actual NPC behavior',
      'and I thought MY takes were bad',
      'imagine typing this and hitting send',
      'the secondhand embarrassment is real',
      'this is a cry for help',
      'my guy thinks he ate',
      'bless your heart',
      'log off and rethink everything',
      'this tweet belongs in a museum of bad opinions',
      'did a bot write this',
      'most coherent twitter user',
      'please go outside and touch a tree',
      'you really woke up and chose violence against common sense',
      'the hottest of garbage takes',
      'I\'ve seen better takes from fortune cookies',
      'this reads like a cry for attention',
      'congratulations this is the dumbest thing I\'ve read today',
      'bro is fighting for his life in these replies',
      'this take is so cold it lowered the room temperature',
      'seek professional help',
      'most original twitter user',
      'least deranged poster',
      'go back to Facebook',
      'your WiFi should have cut out before you posted this',
      'even your autocorrect is embarrassed',
      'the algorithm should bury this',
      'I need eye bleach after reading this',
      'sir this is a Wendy\'s',
      'you\'re living proof that the internet was a mistake',
      'someone come get their uncle',
      'most self-aware poster on this app',
      'main character syndrome is treatable btw',
    ],

    coin: [
      '$YAPPR',
      '$MOONRUG',
      '$COPIUM',
      '$RUGPULL',
      '$BAGHOLD',
      '$NGMI',
      '$WAGMI',
      '$SEETHE',
      '$HOPIUM',
      '$FUDCOIN',
      '$GIGABRAIN',
      '$PEPEMAX',
      '$DUMPEET',
      '$APECOIN',
      '$PONZI42',
      '$LAMBO',
      '$REKTD',
      '$DIAMONDHAND',
      '$YEETCOIN',
      '$TRUSTMEBRO',
      '$EXIT',
      '$SCAMWICK',
      '$PUMPFUN',
      '$ANONFREN',
      '$DEGENX',
      '$BAGHOLDER',
      '$NOTASCAM',
      '$MEMECAP',
      '$DOWNBAD',
      '$UPONLY',
    ],

    shill_phrase: [
      'still early',
      'NFA but DYOR',
      'wagmi',
      'few understand',
      'this is the way',
      'LFG 🚀',
      'not financial advice',
      'gonna make it',
      'we\'re all gonna make it',
      'bullish af',
      'diamond hands only',
      'ngmi if you don\'t ape in',
      'trust the process',
      'moon soon',
      'generational wealth opportunity',
      'the chart speaks for itself',
      'early is the new late',
      'devs are doxxed',
      'audit coming soon',
      'community-driven',
    ],

    overreaction: [
      'this is literally the worst take of 2024',
      'my therapist is going to hear about this',
      'I am calling the authorities',
      'this should be illegal',
      'you have ruined my entire week',
      'my ancestors are rolling in their graves',
      'I\'m going to need a moment',
      'I can feel my life force draining',
      'humanity was a mistake and this proves it',
      'I\'m uninstalling the internet',
      'this is a crime against common sense',
      'I\'m filing a formal complaint',
      'this tweet set us back as a species',
      'I\'m contacting my congressman about this',
      'this is why aliens won\'t visit us',
      'my faith in humanity: shattered',
      'I have never been more offended in my entire life',
      'this tweet should be studied by scientists',
      'you owe me reparations for making me read this',
      'I\'m adding this to my list of reasons to leave the planet',
      'the Geneva Convention should cover this',
      'I am VISIBLY upset',
      'my doctor said to avoid stress and then I saw this tweet',
      'this is a violation of my human rights',
      'I need to call my mom after reading this',
      'congratulations you have broken me',
      'this tweet gave me a migraine',
      'I\'m never recovering from this',
      'the damage is irreversible',
      'I can\'t even look at my phone anymore',
      'this tweet ended my career somehow',
      'I\'m telling everyone I know about this',
      'the trauma from reading this is immeasurable',
      'I have lost the ability to even',
      'every cell in my body just cringed',
      'I aged ten years reading this',
      'my fight-or-flight just activated',
      'I\'m writing a letter to someone important about this',
      'you should be banned from the internet',
      'this tweet physically hurt me',
    ],

    concept: [
      'market dynamics',
      'second-order effects',
      'basic economics',
      'game theory',
      'systems thinking',
      'behavioral psychology',
      'information asymmetry',
      'network effects',
      'comparative advantage',
      'opportunity cost',
      'survivorship bias',
      'selection effects',
      'regression to the mean',
      'base rates',
      'Bayesian reasoning',
      'the principal-agent problem',
      'moral hazard',
      'incentive structures',
      'emergent behavior',
      'Dunning-Kruger',
      'cognitive dissonance',
      'confirmation bias',
      'the Overton window',
      'historical materialism',
      'social contract theory',
      'regulatory capture',
      'Goodhart\'s law',
      'Chesterton\'s fence',
      'Lindy effects',
      'ergodicity',
      'convexity',
      'tail risk',
      'antifragility',
      'revealed preferences',
      'price discovery',
      'supply and demand',
      'diminishing returns',
      'the tragedy of the commons',
      'mechanism design',
      'collective action problems',
    ],

    emoji_spam: [
      '🔥🔥🔥',
      '🚀🚀🚀🌕',
      '💯💯🔥',
      '😍🙌🔥',
      '⭐⭐⭐⭐⭐',
      '🔥💪🏆',
      '✨✨✨',
      '🙏🔥💯',
      '👏👏👏',
      '💎🙌🚀',
      '🎯🔥💯',
      '💪💪🔥',
      '🤝🔥✅',
      '❤️🔥💯',
      '😱🔥🚀',
      '👑👑👑',
      '💰💰🔥',
      '🏆🔥💯',
      '🔥🎯✨',
      '😤🔥💪',
    ],

    backhanded_concern: [
      'you might want to sit this one out',
      'maybe log off for a bit',
      'this reads like you\'re going through something',
      'are you okay? genuinely asking',
      'you seem really stressed and it\'s showing in your tweets',
      'maybe run this by someone you trust before posting',
      'this is the kind of thing you\'ll cringe at in a year',
      'I think you need a break from twitter honestly',
      'your mentions are going to be rough on this one',
      'this is one of those tweets you should sleep on before posting',
      'maybe this isn\'t the platform for working through these feelings',
      'I think you might be in over your head on this topic',
      'is there someone in your life you can talk to about this?',
      'you\'re posting through it and it\'s not going well',
      'this seems like a cry for help disguised as a hot take',
      'you sound tired. like really, really tired',
      'have you considered that maybe this isn\'t your area of expertise?',
      'this is giving "hasn\'t touched grass in three weeks"',
      'maybe take a walk before your next tweet?',
      'your feed has been a lot lately. just want to check in',
      'this tweet has a vibe and the vibe is concerning',
      'I say this gently: this is not the win you think it is',
      'are you posting this ironically? I can\'t tell anymore',
      'everyone goes through rough patches, maybe step away for a bit',
      'not everyone needs to share every thought they have',
      'sometimes the bravest thing is to not tweet',
      'your followers are worried about you and so am I',
      'this reads like it was written at 3am and I mean that in the worst way',
      'maybe journal this one instead of tweeting it',
      'the algorithm is going to eat you alive for this one, just a heads up',
    ],

    unrelated_rant: [
      'why does every restaurant have a QR code menu now',
      'I switched to Linux and my life changed',
      'nobody talks about how bad airport WiFi still is',
      'self-checkout lanes are a scam to make us do free labor',
      'every streaming service is just cable again',
      'the price of eggs is genuinely insane right now',
      'daylight saving time should be abolished immediately',
      'people who recline their seats on planes are sociopaths',
      'USB-C should have happened ten years ago',
      'modern cars have too many screens and not enough buttons',
      'reply all should require a captcha',
      'open floor plans ruined offices forever',
      'why are mattresses so expensive',
      'every app wants to send me notifications now',
      'printers haven\'t improved since 1998',
      'the decline of physical media is a tragedy nobody talks about',
      'roundabouts are objectively better than four-way stops',
      'tipping culture has gotten completely out of hand',
      'smart home devices are just expensive ways to feel spied on',
      'the Oxford comma is not optional and I will die on this hill',
      'subscription models for everything are peak dystopia',
      'phone batteries were better before phones got thin',
      'people who don\'t use turn signals should lose their license',
      'the music industry peaked in the early 2000s',
      'every new social media app is worse than the last one',
      'landlords have never fixed anything in a timely manner in the history of renting',
      'group chats are a form of psychological warfare',
      'the decline of local news is actually really scary',
      'we peaked as a society when we invented the public library',
      'automatic paper towel dispensers never give you enough paper',
      'why does every website need my email now',
      'movie theaters charging $9 for popcorn is criminal',
      'people who play music on speakerphone in public should be fined',
      'standing desks are just a way to feel productive while doing nothing',
      'the fact that fax machines still exist tells you everything about healthcare',
      'parking meters should be illegal',
      'every software update makes things worse',
      'fitted sheets are the hardest thing humans have ever tried to fold',
      'the snooze button is humanity\'s greatest self-sabotage invention',
      'nobody actually reads terms of service and we all know it',
    ],

    spam_product: [
      'bio for a surprise',
      'new project',
      'pinned tweet',
      'latest drop',
      'profile for exclusive content',
      'link in bio',
      'DMs for collabs',
      'new course',
      'free ebook in bio',
      'newsletter',
      'pinned post',
      'latest video',
      'new podcast episode',
      'Telegram group',
      'Discord community',
    ],

    hashtag: [
      '#truth',
      '#facts',
      '#wakeup',
      '#nojoke',
      '#realtalk',
      '#nodebate',
      '#thinkaboutit',
      '#unpopularopinion',
      '#controversial',
      '#istandwithme',
      '#woke',
      '#freedom',
      '#accountability',
      '#justsaying',
      '#letthatsinkdin',
      '#dropthemic',
      '#perspective',
      '#mindblown',
      '#readthatagain',
      '#icantbelieveit',
    ],
  },

  // Identity generation material
  identity: {
    firstNames: [
      'Jake', 'Mike', 'Kyle', 'Chad', 'Bryce', 'Tyler', 'Hunter', 'Cody',
      'Dylan', 'Logan', 'Mason', 'Austin', 'Caleb', 'Brandon', 'Derek',
      'Alex', 'Jordan', 'Taylor', 'Morgan', 'Casey', 'Riley', 'Quinn',
      'Avery', 'Reese', 'Parker', 'Drew', 'Blake', 'Sage', 'Finn',
      'CryptoKing', 'NFTMaxi', 'DeFiDegen', 'TokenLord',
      'truth', 'freedom', 'based', 'alpha', 'sigma', 'grind',
      'realone', 'patriot', 'thinker', 'hustler',
    ],

    lastFragments: [
      'Official', 'Real', 'Based', 'Actual', 'NotABot', 'TheTruth',
      'Enjoyer', 'Maxi', 'Holder', 'Poster', 'Takes', 'Thoughts',
      'Wins', 'Gains', 'Alpha', 'Sigma', 'Grindset', 'Mindset',
    ],

    handlePatterns: [
      '{first}{4digit}',        // jake8294
      '{first}_{fragment}',     // real_thoughts
      '{adj}{noun}{2digit}',    // basedtakes99
      '{first}{year}',          // mike1997
    ],

    adjectives: [
      'based', 'real', 'true', 'actual', 'raw', 'pure', 'big', 'dark',
      'cold', 'hard', 'mad', 'lit', 'hot', 'top', 'main', 'full',
    ],

    nouns: [
      'takes', 'facts', 'truth', 'alpha', 'gains', 'posts', 'chad',
      'king', 'boss', 'wolf', 'lion', 'bear', 'dude', 'bro', 'guy',
    ],
  },
};
