/**
 * Pain Tolerance — Corpus
 *
 * Static data bank: archetype definitions, templates, and slot fillers.
 * Phase 2: Full archetype banks without spam-bot templates.
 */

export const PT_CORPUS = {
  archetypes: [
    {
      id: 'ratio_guy',
      name: 'Ratio Guy',
      weight: 22,
      templates: [
        'ratio',
        'L',
        'nobody asked',
        'cope',
        '{insult}',
        'L + {insult}',
        'ratio + {insult}',
        'didn\'t ask + {insult}',
        'cool story bro',
        'you thought you did something here',
        'this ain\'t it chief',
        'massive L',
        'the audacity of this tweet',
        'go outside',
        'tell me you have no friends without telling me you have no friends',
        'least delusional twitter user',
        'bro really thought he cooked 💀',
        'imagine posting this and thinking it was good',
        'you\'re the reason people leave this app',
        'mid take',
        'the silence from everyone who agrees with you is deafening',
        'bro woke up and chose to be wrong',
        'L take + ratio + {insult}',
        'not reading all that. {insult}',
        'ok and?',
        'genuinely who cares',
        'imagine being this confidently incorrect',
        'the bar was on the floor and you somehow limboed under it',
        'nobody said it but I\'ll say it: this is bad',
        'bro is one tweet away from being airdropped into reality',
        'the cope is industrial-grade today',
        'sir delete your account immediately',
        'not the take, the energy. and not the energy, the everything',
        'bro really posted this and went to bed proud',
        'you know what, never mind',
        'ratio incoming. enjoy your day',
        'the algorithm punished us all for your tweet',
        'couldn\'t have kept this in drafts? truly?',
        'this tweet is what happens when nobody tells you no',
        'Twitter is a mistake and you are exhibit A',
        'you were so close to being quiet today',
        'the wrong person logged on this morning',
        'someone please confiscate his login',
        'bro typed this with his whole chest',
        'you shouldn\'t be allowed near a keyboard',
        'the 15 likes you\'ll get for this from your weirdest mutuals are all you deserve',
        'you really hit send on this one huh',
        'ratio + {insult} + you should be ashamed',
        'the take is bad, the delivery is worse, and you are the worst',
        'tell me you peaked in 2014 without telling me you peaked in 2014',
        'bro is committing crimes against typing',
        'this tweet has the energy of a man who\'s never been told no',
        'screenshot this for the loss porn folder',
        'touch grass, then a curb, then more grass',
        'not even close',
        'wow you really posted that out loud huh',
      ],
    },
    {
      id: 'unhinged_reply_guy',
      name: 'Unhinged Reply Guy',
      weight: 15,
      templates: [
        'I cannot BELIEVE you would say this. {overreaction}. Blocked.',
        'WOW. just WOW. {overreaction}',
        'THIS is what\'s wrong with this website. {overreaction}',
        'I just showed this to my therapist and she started crying',
        'my blood pressure literally just spiked reading this. {overreaction}',
        'I have been SHAKING for the last twenty minutes because of this tweet. {overreaction}',
        'you have NO IDEA the damage this tweet has caused. {overreaction}',
        'I was having a good day until I read this. {overreaction}',
        'actually screaming at my phone right now. {overreaction}',
        'this is genuinely the most harmful thing I have ever read on this website',
        'I am going to remember this tweet on my deathbed and it will ruin my last moments',
        'every day I log on and someone like you makes it worse. {overreaction}',
        'DO YOU EVEN HEAR YOURSELF?? {overreaction}',
        'I just threw my phone across the room reading this. {overreaction}',
        'this tweet is violence. actual violence. {overreaction}',
        'I need to lie down after reading this. {overreaction}',
        'showed this tweet to my cat and he hissed at the screen',
        'I have officially lost all faith in humanity thanks to this ONE tweet. {overreaction}',
        'bro dropped this take and thought we\'d all just be OKAY with it??? {overreaction}',
        'the NERVE. the ABSOLUTE AUDACITY. {overreaction}',
        'I am LITERALLY screaming. {overreaction}',
        'I have read this tweet 47 times and each time it gets worse. {overreaction}',
        'I had to step away from my computer. I had to GO OUTSIDE. {overreaction}',
        'I am telling everyone I know about this tweet right now. {overreaction}',
        'I just read this to my coworkers and we all went silent',
        'my partner asked why I was crying and I had to show them this tweet',
        'not me sobbing in the Walmart parking lot reading this',
        'I cannot BREATHE. {overreaction}',
        'WHO RAISED YOU. WHO. {overreaction}',
        'the fact that this is allowed on the internet. {overreaction}',
        'this tweet has aged me TEN YEARS. {overreaction}',
        'I am muting your name from every platform I exist on',
        'I genuinely don\'t know how to come back from reading this. {overreaction}',
        'I am calling everyone I know to warn them about you',
        'I cannot remember the last time a tweet broke me like this. {overreaction}',
        'I just got out of the shower to type this. you don\'t understand. {overreaction}',
        'you have given me material to talk about in therapy for MONTHS',
        'I will be unwell about this tweet for the foreseeable future. {overreaction}',
        'I feel personally attacked by this tweet that has NOTHING to do with me. {overreaction}',
        'every fiber of my being is REJECTING this. {overreaction}',
        'I am going to bed early tonight because of you specifically',
        'I am DONE with the internet. genuinely done. {overreaction}',
      ],
    },
    {
      id: 'pseudo_intellectual',
      name: 'Pseudo-Intellectual',
      weight: 12,
      templates: [
        'tell me you don\'t understand {concept} without telling me you don\'t understand {concept}',
        'this is what happens when people who don\'t understand {concept} try to have opinions',
        'actually, if you understood {concept}, you wouldn\'t have posted this',
        'I studied {concept} for years and this is the most reductive take I\'ve ever seen',
        'the Dunning-Kruger is strong with this one. read up on {concept}',
        'imagine not understanding {concept} and still tweeting confidently about it',
        'this take reveals a fundamental misunderstanding of {concept}',
        'I would explain why you\'re wrong but it requires understanding {concept}',
        'sir, this is not the flex you think it is. {concept} says otherwise',
        'spoken like someone who has never once engaged with {concept}',
        'the irony of posting this while clearly not understanding {concept} is *chef\'s kiss*',
        'maybe read a book on {concept} before tweeting next time',
        'this is the kind of take that makes {concept} researchers weep',
        'my brother in christ, {concept} has entered the chat',
        'fascinating case study in not understanding {concept}',
        'you\'re so close to getting it but {concept} is clearly not your strong suit',
        'ah yes, the classic "I don\'t understand {concept}" tweet. seen a million of these',
        'this screams "I read one article about {concept} and formed my entire worldview"',
        'it\'s giving {concept} illiteracy',
        'not to be that guy but {concept} literally disproves everything you just said',
        'bro skipped the chapter on {concept} and it shows',
        'every {concept} expert I know is laughing at this tweet rn',
        'I\'d respond seriously but this take requires a working understanding of {concept}, and clearly we\'re not there yet',
        'this tweet is a textbook example of what happens when {concept} fails to enter the chat',
        'the {concept} community is going to have a field day with this one',
        'respectfully: {concept}. that\'s the entire post. that\'s all you needed to know',
        'there\'s a whole subfield dedicated to debunking exactly this take. it\'s called {concept}',
        'I recommend reading literally anything about {concept} before tweeting again',
        'you skipped {concept} and went straight to confidence. unfortunate sequence',
        'this is the kind of take that makes me grateful I learned about {concept}',
        'what you\'re describing has a name. it\'s called {concept}, and you\'ve stumbled into it accidentally',
        'please workshop this take with a {concept} reading group before next time',
        'I\'d say more but {concept} already says it better',
        'the specific kind of wrong this tweet is has been studied. read about {concept}',
        'it\'s {concept}, not whatever this is',
        'tell me you\'ve never sat with the implications of {concept} for more than thirty seconds',
        'bro discovered an opinion and skipped {concept} entirely',
        'the literature on {concept} called and it would like you to stop',
        'if you\'d read even half a paper on {concept} you would be ashamed of this tweet',
      ],
    },
    {
      id: 'sneering_dismissal',
      name: 'Sneering Dismissal',
      weight: 18,
      templates: [
        'this tweet is an insult to everyone who reads it',
        'every time you post something I lose more faith that things will be okay',
        'the confidence in this post is inversely proportional to its quality',
        'just an absolutely spectacular failure of a take',
        'you are embarrassing yourself and I feel nothing but contempt',
        'not a single redeemable word in this entire tweet',
        'I\'ve read dumber things but I really had to think about it',
        'this is what rock bottom looks like from the inside',
        'you should be legally required to warn people before posting this stuff',
        'the people who like this tweet are worse than the tweet itself',
        'I can actually feel my opinion of you dropping in real time',
        'posting this required a level of obliviousness that most people could never achieve',
        'a perfect encapsulation of why everyone is getting dumber',
        'whoever raised you should see this tweet',
        'you clearly have never been told no in your entire life',
        'this is what it looks like when someone has never faced consequences',
        'the audacity is frankly impressive. the take is not.',
        'I hope you never find out how many people laughed at this',
        'chronically, terminally, irreversibly online',
        'please never reproduce this energy ever again',
        'objectively the worst tweet of the week and it\'s only Monday',
        'every word in this sentence is wrong in a different way',
        'I actively dislike you now and I didn\'t know you existed 30 seconds ago',
        'this is going in my personal hall of shame',
        'I am genuinely appalled and I rarely get genuinely appalled at tweets',
        'this is the kind of post that should come with a content warning for the people who care about you',
        'every word here is a brick in the cathedral of your own embarrassment',
        'I\'d ratio you but you\'ve already done that to yourself',
        'imagine being this unaware in public. on purpose. with confidence',
        'you have cracked the code on being insufferable',
        'the unearned confidence of this tweet is doing a lot of heavy lifting',
        'posting this implies a profound lack of friends willing to tell you the truth',
        'no thoughts originated in this house, only echoes',
        'it\'s astonishing how you manage to be this wrong this often',
        'this is the kind of tweet that makes me close the app and consider my life choices',
        'I have lower expectations of you now than I had three minutes ago, which is impressive',
        'whatever moved you to type this, please get rid of it. it is not your friend',
        'you have managed to be both boring and offensive simultaneously, which takes real talent',
        'the silence after reading this was loud',
        'there is no one more confident than the person who has nothing to be confident about',
        'every reply guy in your mentions just got promoted',
        'please retire from posting. for everyone',
        'the people who agree with this tweet are the same people I hope I never meet',
        'you are everything wrong with this app concentrated into one tweet',
        'this is a masterclass in posting yourself into a hole',
        'congratulations on the worst contribution to the discourse this week',
        'I\'ve seen better takes scrawled on bathroom walls',
        'the tweet is bad. the implication that you thought it was good is worse',
        'what part of you thought this was the move',
        'I want to put this tweet in a glass case and label it "warning to others"',
      ],
    },
    {
      id: 'concern_troll',
      name: 'Concern Troll',
      weight: 8,
      templates: [
        'I mean this in the nicest way but {backhanded_concern}',
        'not trying to be mean but {backhanded_concern}',
        'genuinely asking this out of concern: {backhanded_concern}',
        'hey, just looking out for you here — {backhanded_concern}',
        'I say this with love: {backhanded_concern}',
        'no hate, but honestly? {backhanded_concern}',
        'this is coming from a good place I promise: {backhanded_concern}',
        'look, I\'m not judging, but {backhanded_concern}',
        'as someone who cares about you as a stranger on the internet: {backhanded_concern}',
        'I hope you have people in your life who can tell you this gently: {backhanded_concern}',
        'don\'t take this the wrong way but {backhanded_concern}',
        'with all due respect, and I mean that sincerely, {backhanded_concern}',
        'I\'m sure you mean well but {backhanded_concern}',
        'just some friendly feedback: {backhanded_concern}',
        'no offense intended but {backhanded_concern}',
        'as a friend, well, a follower, well, someone who saw this tweet: {backhanded_concern}',
        'this is hard to say but someone needs to: {backhanded_concern}',
        'I really don\'t want to pile on here but {backhanded_concern}',
        'I know this will sound harsh but it\'s for your own good: {backhanded_concern}',
        'bless your heart, but {backhanded_concern}',
        'I only say this because I care: {backhanded_concern}',
        'I\'m genuinely worried about you after reading this — {backhanded_concern}',
        'look, no judgment, just observation: {backhanded_concern}',
        'I really hope someone in your life is paying attention because {backhanded_concern}',
        'I\'m sending this with love I promise but {backhanded_concern}',
        'just a thought from someone who\'s seen a lot of bad tweets: {backhanded_concern}',
        'I\'d hate to see you keep going down this road. {backhanded_concern}',
        'this is the kind of tweet I\'d want a friend to flag for me, so: {backhanded_concern}',
        'I know we don\'t know each other but {backhanded_concern}',
        'it would be a disservice not to say it: {backhanded_concern}',
        'for what it\'s worth — and I mean this kindly — {backhanded_concern}',
      ],
    },
    {
      id: 'off_topic_ranter',
      name: 'Off-Topic Ranter',
      weight: 10,
      templates: [
        'speaking of which, {unrelated_rant}',
        'this reminds me — {unrelated_rant}',
        'not related but {unrelated_rant}',
        'idk why this made me think of this but {unrelated_rant}',
        'anyway {unrelated_rant}',
        'ok but can we talk about how {unrelated_rant}',
        'unrelated but {unrelated_rant}',
        'nobody\'s talking about the real issue here which is that {unrelated_rant}',
        'sure but meanwhile {unrelated_rant}',
        'while we\'re all distracted by this tweet, {unrelated_rant}',
        'this is fine but honestly {unrelated_rant}',
        'I\'ll get to this in a sec but first: {unrelated_rant}',
        'cool tweet. anyway, {unrelated_rant}',
        'ok I hear you but also {unrelated_rant}',
        'you know what\'s actually important? {unrelated_rant}',
        'since everyone\'s here: {unrelated_rant}',
        'weird hill to die on when {unrelated_rant}',
        'the REAL take is that {unrelated_rant}',
        'I know this is off topic but {unrelated_rant}',
        'that\'s great and all but {unrelated_rant}',
        'filing this tweet under "things that don\'t matter" because {unrelated_rant}',
        'not to derail but {unrelated_rant}',
        'tangent but actually relevant: {unrelated_rant}',
        'your tweet is fine but personally I\'d rather discuss {unrelated_rant}',
        'bigger fish to fry, namely: {unrelated_rant}',
        'imagine focusing on this when {unrelated_rant}',
        'we have bigger problems than your opinion. for example, {unrelated_rant}',
        'respectfully changing the subject: {unrelated_rant}',
        'your tweet is fine I guess but the actual scandal is that {unrelated_rant}',
        'the audacity to post this when {unrelated_rant}',
        'nobody is going to address that {unrelated_rant}? alright then',
        'meanwhile in the real world: {unrelated_rant}',
      ],
    },
    {
      id: 'one_word_oracle',
      name: 'One-Word Oracle',
      weight: 5,
      templates: [
        'no',
        'wrong',
        'lol',
        'mid',
        'yikes',
        'nah',
        'false',
        'cap',
        'cringe',
        'oof',
        'bruh',
        'next',
        'pass',
        'delete this',
        'who asked',
        'embarrassing',
        'awful',
        'pathetic',
        'tragic',
        'delusional',
        'clown behavior',
        'skill issue',
        'rejected',
        'flagged',
        'reported',
        '💀',
        '🤡',
        '🗑️',
        '😬',
        'abysmal',
        'get off this app',
        'lmao no',
        'incorrect',
        'delete',
        'block',
        'goofy',
        'weird flex',
        'unfortunate',
        'disgraceful',
        'painful',
        'hard pass',
        'not it',
        'dogwater',
        '🚮',
        'dire',
        'grim',
        'ratioed',
        'cooked',
        'done',
        'over',
        'sit down',
        '🥴',
        'humiliating',
        'dreadful',
        'appalling',
      ],
    },
  ],

  fillers: {
    insult: [
      'this ain\'t it',
      'touch grass',
      'most sane twitter user',
      'least brain-damaged take',
      'certified clown behavior',
      'you dropped this 🤡',
      'absolute room-temperature IQ take',
      'bro thinks he\'s deep',
      'galaxy brain moment',
      'average main character syndrome',
      'tell your mom I said hi',
      'least chronically online take',
      'bro peaked in middle school',
      'the bar is in hell and you brought a shovel',
      'most well-adjusted reply guy',
      'this is why nobody follows you back',
      'congrats on the worst take of the day',
      'you\'re not even wrong you\'re just boring',
      'actual NPC behavior',
      'and I thought MY takes were bad',
      'imagine typing this and hitting send',
      'the secondhand embarrassment is real',
      'this is a cry for help',
      'my guy thinks he ate',
      'bless your heart',
      'log off and rethink everything',
      'this tweet belongs in a museum of bad opinions',
      'did a bot write this',
      'most coherent twitter user',
      'please go outside and touch a tree',
      'you really woke up and chose violence against common sense',
      'the hottest of garbage takes',
      'I\'ve seen better takes from fortune cookies',
      'this reads like a cry for attention',
      'congratulations this is the dumbest thing I\'ve read today',
      'bro is fighting for his life in these replies',
      'this take is so cold it lowered the room temperature',
      'seek professional help',
      'most original twitter user',
      'least deranged poster',
      'go back to Facebook',
      'your WiFi should have cut out before you posted this',
      'even your autocorrect is embarrassed',
      'the algorithm should bury this',
      'I need eye bleach after reading this',
      'sir this is a Wendy\'s',
      'you\'re living proof that the internet was a mistake',
      'someone come get their uncle',
      'most self-aware poster on this app',
      'main character syndrome is treatable btw',
      'this is what posting through dehydration looks like',
      'you need a hobby that isn\'t typing',
      'your phone deserves better',
      'bro thinks he\'s spitting facts and it\'s just spit',
      'the most confident L of the week',
      'your mentions are about to be a national park',
      'your followers must be exhausted',
      'you should have to apply for a posting license',
      'a tweet so bad even the algorithm is trying to bury it',
      'you are the human equivalent of unsolicited feedback',
      'please be quieter on main',
      'every mute button in this app just sighed',
      'you tweet like someone who has never been embarrassed',
      'you sound like a podcast nobody asked for',
      'please consider a vow of silence',
      'bro typed this and refilled his coffee like he did something',
      'you are speed-running the worst-takes leaderboard',
      'every word in this tweet is a personal failure',
      'your timeline must be a war zone of bad opinions',
      'the people in your life owe you a serious conversation',
      'you sound like a man who has interrupted every meeting he\'s ever been in',
      'you tweet like you\'ve never been corrected',
      'the energy of someone who lost an argument with a barista this morning',
      'imagine logging on with this attitude. cardio',
      'you are a cautionary tale wearing a profile picture',
      'I can taste the desperation through the screen',
      'the entire app just got dumber',
      'please log off and apologize to your loved ones',
      'your wifi was the only thing standing between us and this tweet, and it failed',
      'the most well-adjusted thing about you is your ability to log on',
      'you have the rhetorical strength of a wet napkin',
      'your whole posting career is one long apology in the making',
      'the algorithm bumping this tweet was workplace negligence',
      'most easily embarrassed twitter user simulator',
      'you have the take quality of a discount fortune cookie',
      'you sound like you\'ve never had to live with the consequences of a sentence',
      'bro is auditioning for a role nobody cast',
      'you have the social calibration of a smoke alarm',
      'every screenshot of this tweet is going to outlive you',
      'the cringe is so dense it\'s distorting space-time around your profile',
      'congrats, you\'re the worst tweet I\'ve seen since the last time I logged on',
      'you have the stage presence of a deleted reply',
      'you have the comedic timing of a nine-hour conference call',
    ],

    overreaction: [
      'this is literally the worst take of 2024',
      'my therapist is going to hear about this',
      'I am calling the authorities',
      'this should be illegal',
      'you have ruined my entire week',
      'my ancestors are rolling in their graves',
      'I\'m going to need a moment',
      'I can feel my life force draining',
      'humanity was a mistake and this proves it',
      'I\'m uninstalling the internet',
      'this is a crime against common sense',
      'I\'m filing a formal complaint',
      'this tweet set us back as a species',
      'I\'m contacting my congressman about this',
      'this is why aliens won\'t visit us',
      'my faith in humanity: shattered',
      'I have never been more offended in my entire life',
      'this tweet should be studied by scientists',
      'you owe me reparations for making me read this',
      'I\'m adding this to my list of reasons to leave the planet',
      'the Geneva Convention should cover this',
      'I am VISIBLY upset',
      'my doctor said to avoid stress and then I saw this tweet',
      'this is a violation of my human rights',
      'I need to call my mom after reading this',
      'congratulations you have broken me',
      'this tweet gave me a migraine',
      'I\'m never recovering from this',
      'the damage is irreversible',
      'I can\'t even look at my phone anymore',
      'this tweet ended my career somehow',
      'I\'m telling everyone I know about this',
      'the trauma from reading this is immeasurable',
      'I have lost the ability to even',
      'every cell in my body just cringed',
      'I aged ten years reading this',
      'my fight-or-flight just activated',
      'I\'m writing a letter to someone important about this',
      'you should be banned from the internet',
      'this tweet physically hurt me',
      'I am physically unwell now',
      'I am drafting a strongly worded letter to nobody in particular',
      'I\'m reading this to my mom over the phone right now',
      'my entire afternoon is ruined',
      'the trauma is layered. it has notes. there\'s a top note and a finish',
      'I\'m going to mention this tweet at my next family gathering',
      'I now distrust everyone who liked this',
      'I\'m telling my children about this someday',
      'I\'m logging the precise hour and minute I read this in my journal',
      'I\'m going to remember exactly where I was when I read this',
      'I\'m restructuring my whole week around recovering from this tweet',
      'every plant in my house just wilted in solidarity',
      'I\'m getting up and going for a walk. you\'ve cost me my afternoon',
      'every alarm in my brain is going off',
      'I just sighed so hard my coworker asked if I\'m okay',
      'I will be unable to focus for the rest of the day',
      'you\'ve ruined a perfectly good Thursday for me',
      'I just experienced what I can only describe as a thought event',
      'I\'m calling out of work tomorrow because of this tweet',
      'the floor cracked open beneath me and I fell into bad-tweet hell',
      'I am drafting a complaint to the developers of this app',
      'I\'m starting a support group for people who have read this tweet',
      'I might press charges, the lawyers are looking into it',
      'I\'m filing a noise complaint against your typing',
      'you have unlocked an emotion I\'d rather not have',
      'the second-hand embarrassment is enough to power a small city',
      'I\'m staring at the ceiling reconsidering everything',
      'I am going to scream into a pillow and you\'ll never know',
      'every cell in my body has filed a grievance',
    ],

    concept: [
      'market dynamics',
      'second-order effects',
      'basic economics',
      'game theory',
      'systems thinking',
      'behavioral psychology',
      'information asymmetry',
      'network effects',
      'comparative advantage',
      'opportunity cost',
      'survivorship bias',
      'selection effects',
      'regression to the mean',
      'base rates',
      'Bayesian reasoning',
      'the principal-agent problem',
      'moral hazard',
      'incentive structures',
      'emergent behavior',
      'Dunning-Kruger',
      'cognitive dissonance',
      'confirmation bias',
      'the Overton window',
      'historical materialism',
      'social contract theory',
      'regulatory capture',
      'Goodhart\'s law',
      'Chesterton\'s fence',
      'Lindy effects',
      'ergodicity',
      'convexity',
      'tail risk',
      'antifragility',
      'revealed preferences',
      'price discovery',
      'supply and demand',
      'diminishing returns',
      'the tragedy of the commons',
      'mechanism design',
      'collective action problems',
      'epistemic humility',
      'revealed vs stated preferences',
      'power dynamics',
      'narrative inversion',
      'path dependency',
      'coordination failures',
      'intertemporal tradeoffs',
      'risk-adjusted returns',
      'Hanlon\'s razor',
      'Occam\'s razor',
      'Cunningham\'s law',
      'Arrow\'s impossibility theorem',
      'the prisoner\'s dilemma',
      'the bystander effect',
      'the peer review process',
      'replication crises',
      'correlation vs causation',
      'the streetlight effect',
      'the curse of dimensionality',
      'the no-free-lunch theorem',
      'endogeneity',
      'the efficient market hypothesis',
      'epistemic closure',
      'motivated reasoning',
      'loss aversion',
      'hyperbolic discounting',
      'negativity bias',
      'framing effects',
      'the availability heuristic',
    ],

    backhanded_concern: [
      'you might want to sit this one out',
      'maybe log off for a bit',
      'this reads like you\'re going through something',
      'are you okay? genuinely asking',
      'you seem really stressed and it\'s showing in your tweets',
      'maybe run this by someone you trust before posting',
      'this is the kind of thing you\'ll cringe at in a year',
      'I think you need a break from twitter honestly',
      'your mentions are going to be rough on this one',
      'this is one of those tweets you should sleep on before posting',
      'maybe this isn\'t the platform for working through these feelings',
      'I think you might be in over your head on this topic',
      'is there someone in your life you can talk to about this?',
      'you\'re posting through it and it\'s not going well',
      'this seems like a cry for help disguised as a hot take',
      'you sound tired. like really, really tired',
      'have you considered that maybe this isn\'t your area of expertise?',
      'this is giving "hasn\'t touched grass in three weeks"',
      'maybe take a walk before your next tweet?',
      'your feed has been a lot lately. just want to check in',
      'this tweet has a vibe and the vibe is concerning',
      'I say this gently: this is not the win you think it is',
      'are you posting this ironically? I can\'t tell anymore',
      'everyone goes through rough patches, maybe step away for a bit',
      'not everyone needs to share every thought they have',
      'sometimes the bravest thing is to not tweet',
      'your followers are worried about you and so am I',
      'this reads like it was written at 3am and I mean that in the worst way',
      'maybe journal this one instead of tweeting it',
      'the algorithm is going to eat you alive for this one, just a heads up',
      'this tweet is going to be screenshotted and you\'re not going to like why',
      'your timeline is starting to look like a public diary, and not in a fun way',
      'your followers are private-message-each-othering about this tweet',
      'you\'re doing the thing again. the thing where you tweet through it',
      'everyone in your group chat has seen this and is choosing not to mention it',
      'your future self will thank you for deleting this immediately',
      'there\'s a version of you in the next room screaming "no, don\'t post that"',
      'I would block you for your own sake but I want to keep watching',
      'I worry about the trend line of your tweets, not just this one',
      'someone close to you needs to take your phone tonight',
      'I\'m only saying this because nobody else seems willing to',
      'the kindest thing I could do right now is not engage further',
      'genuinely, when did you last sleep? I need to know',
      'your tweets have a "before something happened" quality lately',
      'there\'s a long road back from a tweet like this and I hope you walk it',
      'posting through a rough patch is brave but also a choice with consequences',
      'you might not want to scroll the replies for a few hours',
      'you have people in your life who will pretend they didn\'t see this. take comfort in that',
      'I\'d rather not see the version of you that posted this',
      'I think you might be the last person who hasn\'t realized this is bad',
    ],

    unrelated_rant: [
      'why does every restaurant have a QR code menu now',
      'I switched to Linux and my life changed',
      'nobody talks about how bad airport WiFi still is',
      'self-checkout lanes are a scam to make us do free labor',
      'every streaming service is just cable again',
      'the price of eggs is genuinely insane right now',
      'daylight saving time should be abolished immediately',
      'people who recline their seats on planes are sociopaths',
      'USB-C should have happened ten years ago',
      'modern cars have too many screens and not enough buttons',
      'reply all should require a captcha',
      'open floor plans ruined offices forever',
      'why are mattresses so expensive',
      'every app wants to send me notifications now',
      'printers haven\'t improved since 1998',
      'the decline of physical media is a tragedy nobody talks about',
      'roundabouts are objectively better than four-way stops',
      'tipping culture has gotten completely out of hand',
      'smart home devices are just expensive ways to feel spied on',
      'the Oxford comma is not optional and I will die on this hill',
      'subscription models for everything are peak dystopia',
      'phone batteries were better before phones got thin',
      'people who don\'t use turn signals should lose their license',
      'the music industry peaked in the early 2000s',
      'every new social media app is worse than the last one',
      'landlords have never fixed anything in a timely manner in the history of renting',
      'group chats are a form of psychological warfare',
      'the decline of local news is actually really scary',
      'we peaked as a society when we invented the public library',
      'automatic paper towel dispensers never give you enough paper',
      'why does every website need my email now',
      'movie theaters charging $9 for popcorn is criminal',
      'people who play music on speakerphone in public should be fined',
      'standing desks are just a way to feel productive while doing nothing',
      'the fact that fax machines still exist tells you everything about healthcare',
      'parking meters should be illegal',
      'every software update makes things worse',
      'fitted sheets are the hardest thing humans have ever tried to fold',
      'the snooze button is humanity\'s greatest self-sabotage invention',
      'nobody actually reads terms of service and we all know it',
      'every podcast intro is now exactly four minutes too long',
      'airline boarding groups are a class system in disguise',
      'shrinkflation has gotten so bad I can\'t trust a chip bag anymore',
      'every coffee shop now plays music engineered to make you leave',
      'delivery apps add fees to the fees',
      'every YouTube ad is now ninety seconds of someone whispering',
      'gas station bathrooms are an unregulated industry',
      'every email signature is a small autobiography now',
      'every product review is either an essay or a single emoji',
      'gift cards are scams with branding',
      'every passcode field disagrees about character requirements',
      'every cooking recipe is preceded by a thousand-word backstory',
      'work calendars treat every fifteen minutes as a billable invasion',
      'every flight is now boarding "in the next several minutes" forever',
      'every laptop fan sounds like it\'s trying to escape the chassis',
      'every captcha now requires me to identify a traffic light I cannot see',
      'every paywall is just a worse version of a library card',
      'the death of Google Reader is still unsolved cultural homicide',
      'every grocery store reorganized aisles for vibes and now nobody can find rice',
      'we are one ad-supported toaster away from collective collapse',
      'every restaurant chair is now slightly too low on purpose',
      'gym etiquette has cratered. people just stand around now',
      'every product description starts with "introducing"',
      'every airport has the same three stores and yet none of them sell water',
      'every hotel TV makes you sign in to your own Netflix',
      'every meeting could have been an email and every email could have been silence',
      'every news app is just push notifications about other news apps',
    ],

  },

  // Identity generation material
  identity: {
    firstNames: [
      'Jake', 'Mike', 'Kyle', 'Chad', 'Bryce', 'Tyler', 'Hunter', 'Cody',
      'Dylan', 'Logan', 'Mason', 'Austin', 'Caleb', 'Brandon', 'Derek',
      'Alex', 'Jordan', 'Taylor', 'Morgan', 'Casey', 'Riley', 'Quinn',
      'Avery', 'Reese', 'Parker', 'Drew', 'Blake', 'Sage', 'Finn',
      'truth', 'freedom', 'based', 'alpha', 'sigma', 'grind',
      'realone', 'patriot', 'thinker', 'hustler',
    ],

    lastFragments: [
      'Official', 'Real', 'Based', 'Actual', 'NotABot', 'TheTruth',
      'Enjoyer', 'Maxi', 'Holder', 'Poster', 'Takes', 'Thoughts',
      'Wins', 'Gains', 'Alpha', 'Sigma', 'Grindset', 'Mindset',
    ],

    handlePatterns: [
      '{first}{4digit}',        // jake8294
      '{first}_{fragment}',     // real_thoughts
      '{adj}{noun}{2digit}',    // basedtakes99
      '{first}{year}',          // mike1997
    ],

    adjectives: [
      'based', 'real', 'true', 'actual', 'raw', 'pure', 'big', 'dark',
      'cold', 'hard', 'mad', 'lit', 'hot', 'top', 'main', 'full',
    ],

    nouns: [
      'takes', 'facts', 'truth', 'alpha', 'gains', 'posts', 'chad',
      'king', 'boss', 'wolf', 'lion', 'bear', 'dude', 'bro', 'guy',
    ],

    profileBios: {
      default: [
        'posting through it professionally',
        'bad take collector. replies are my cardio.',
        'online in a way my family worries about',
        'unlicensed opinion haver',
        'here for discourse, unfortunately',
        'microdosing consequences and screen time',
        'public diary with worse lighting',
        'archive of thoughts that should have stayed drafts',
        'doing the work, which is mostly arguing',
        'currently losing an argument to the timeline',
      ],
      ratio_guy: [
        'ratio consultant. no refunds.',
        'I see bad posts and I say something',
        'career reply guy, amateur menace',
        'keeping score because somebody has to',
        'your favorite poster\'s least favorite reply',
        'specializing in short replies and long grudges',
      ],
      unhinged_reply_guy: [
        'emotionally available to every bad tweet',
        'the timeline keeps hurting me and I keep coming back',
        'screaming into the void with receipts',
        'currently making this about me',
        'one notification away from a public spiral',
        'responds quickly, regrets slowly',
      ],
      pseudo_intellectual: [
        'independent researcher in {concept} and bad vibes',
        'systems thinker, discourse enjoyer, footnote menace',
        'reading the room through a theoretical framework',
        'ask me about {concept} at your own risk',
        'overexplaining simple things since 2012',
        'citation needed, personality optional',
      ],
      sneering_dismissal: [
        'here to lower expectations',
        'professional hater, amateur historian',
        'documenting the decline in real time',
        'I judge because I care about standards',
        'not mad, just disappointed in advance',
        'curating a museum of avoidable posts',
      ],
      concern_troll: [
        'checking in, but make it judgmental',
        'wellness advocate for people who should log off',
        'saying this with love and visible contempt',
        'gentle feedback, sharpened edges',
        'here if you need support deleting that',
        'emotionally invested in your drafts folder',
      ],
      off_topic_ranter: [
        'this connects to my larger point about everything',
        'available for tangents, unavailable for the point',
        'local crank, global concerns',
        'turning every thread into a town hall',
        'not derailing, broadening the conversation',
        'single-issue voter, many issues',
      ],
      one_word_oracle: [
        'minimalist hater',
        'saying less because it is enough',
        'one word, maximum damage',
        'brevity is the soul of contempt',
        'typing from the judgment balcony',
        'no bio, just vibes and verdicts',
      ],
    },

    mutualFollowers: [
      'm_11', 'Emergent', 'Steve James', 'low quality facts', 'maya',
      'nora', 'caleb.txt', 'sasha', 'riley', 'burner king', 'alex',
      'casey', 'jordan', 'posting goblin', 'internet user', 'no context eli',
      'sam', 'quinn', 'drew', 'parker', 'the group chat', 'morgan',
      'local maximum', 'ari', 'bad take enjoyer', 'taylor', 'sage',
      'finn', 'browser tab 47', 'professional lurker', 'derek', 'logan',
    ],
  },
};
